#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://media.rex007.workers.dev/0:/cirrus-ci/ccache/ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50
time tar xf ccache.tar.gz
find ccache.tar.gz -delete
